name       : libplist
version    : 1.12
release    : 3
source     :
    - git|https://github.com/libimobiledevice/libplist.git : 8ad21e6b59e5e5a3104660f17ad2b0e9122edecf
license    : GPL-2.0
component  : multimedia.library
summary    : A small portable C library to handle Apple Property List files in binary or XML.
description: |
    A small portable C library to handle Apple Property List files in binary or XML.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
