name       : libplist
version    : 2.2.0
release    : 8
source     :
    - git|https://github.com/libimobiledevice/libplist.git : 45d99de4e149637f00225c36a9c1712eef2ce510
license    : GPL-2.0-or-later
component  : multimedia.library
summary    : A small portable C library to handle Apple Property List files in binary
    or XML.
description: |
    A small portable C library to handle Apple Property List files in binary or XML.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
